import { db, type Song } from '$db/db';
import { synth_options_default } from '$db/stores.js';
import { redirect } from '@sveltejs/kit';

// TODO: set up demos

// 15 step - https://www.youtube.com/watch?v=YEj4tKq5UTE
const drums_15step = [
	// intro
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	['CP'],
	['OH'],
	['CP', 'CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	[],
	['CP', 'OH'],
	['CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	['CP'],
	['OH'],
	['CP', 'CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	[],
	['CP', 'OH'],
	['CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	['CP'],
	['OH'],
	['CP', 'CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	[],
	['CP', 'OH'],
	['CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	['CP'],
	['OH'],
	['CP', 'CH'],
	['CH'],
	['CP', 'OH'],
	[],
	['LT', 'BD'],
	[],
	['CP', 'OH'],
	['CH'],
	[],
	['CP', 'OH'],
	['CH'],
	['CH'],
	['CP', 'OH'],
	[],
	// transition
	['LT', 'BD'],
	[],
	['OH', 'SD'],
	['CH'],
	['CH'],
	['SD', 'CH'],
	['BD', 'CH'],
	['BD', 'CH'],
	['SD', 'CH'],
	['CH'],
	['LT', 'BD', 'CH'],
	['CH'],
	['SD', 'CH'],
	['CH'],
	['OH'],
	['SD', 'BD', 'CH'],
	['BD', 'CH'],
	['BD', 'CH'],
	['SD', 'CH'],
	[],
	// Main Rhythm
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['CP', 'OH'],
	['SD', 'CH'],
	['CP', 'LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	['CH'],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['OH'],
	['SD', 'CP', 'CH'],
	['LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	[],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['CP', 'OH'],
	['SD', 'CH'],
	['CP', 'LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	['CH'],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['OH'],
	['SD', 'CP', 'CH'],
	['LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	[],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['CP', 'OH'],
	['SD', 'CH'],
	['CP', 'LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	['CH'],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['OH'],
	['SD', 'CP', 'CH'],
	['LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	[],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['CP', 'OH'],
	['SD', 'CH'],
	['CP', 'LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	['CH'],
	['LT', 'BD', 'OH', 'CY'],
	['SD', 'CH'],
	['SD', 'CP', 'OH'],
	['SD', 'CH'],
	['OH'],
	['SD', 'CP', 'CH'],
	['LT', 'BD', 'OH'],
	['LT', 'BD', 'CH'],
	['SD', 'CP', 'OH'],
	[],
];
const melody_15step = Array(drums_15step.length).fill([]);

const demos: { [key: string]: Song } = {
	'15step': {
		title: 'DEMO | 15 Step - Radiohead (drums)',
		melody: melody_15step,
		drums: drums_15step,
		options: {
			bpm: 91,
			drumkit: 'TR808',
			// TODO: synth options for demo
			synth: synth_options_default,
		},
	},
};

export const load = async ({ params }) => {
	const demo = demos[params.slug];

	if (!demo) {
		throw redirect(307, '/demos');
	}

	const existing = await db.songs.get({ title: demo.title });
	if (existing) {
		throw redirect(303, `/songs/${existing.id}`);
	}

	const new_id = await db.songs.add(demo);
	throw redirect(303, `/songs/${new_id}`);
};

export const ssr = false;
